//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CPPCXParser.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CPPCXParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface ICPPCXParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslationUnit([NotNull] CPPCXParser.TranslationUnitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpression([NotNull] CPPCXParser.PrimaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.idExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdExpression([NotNull] CPPCXParser.IdExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.unqualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnqualifiedId([NotNull] CPPCXParser.UnqualifiedIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedId([NotNull] CPPCXParser.QualifiedIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.nestedNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNestedNameSpecifier([NotNull] CPPCXParser.NestedNameSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaExpression([NotNull] CPPCXParser.LambdaExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.lambdaIntroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaIntroducer([NotNull] CPPCXParser.LambdaIntroducerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.lambdaCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaCapture([NotNull] CPPCXParser.LambdaCaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.captureDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureDefault([NotNull] CPPCXParser.CaptureDefaultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.captureList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaptureList([NotNull] CPPCXParser.CaptureListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCapture([NotNull] CPPCXParser.CaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.simpleCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleCapture([NotNull] CPPCXParser.SimpleCaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitcapture([NotNull] CPPCXParser.InitcaptureContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.lambdaDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLambdaDeclarator([NotNull] CPPCXParser.LambdaDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfixExpression([NotNull] CPPCXParser.PostfixExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typeIdOfTheTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeIdOfTheTypeId([NotNull] CPPCXParser.TypeIdOfTheTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] CPPCXParser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.pseudoDestructorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPseudoDestructorName([NotNull] CPPCXParser.PseudoDestructorNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] CPPCXParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] CPPCXParser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.newExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewExpression([NotNull] CPPCXParser.NewExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.newPlacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewPlacement([NotNull] CPPCXParser.NewPlacementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.newTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewTypeId([NotNull] CPPCXParser.NewTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.newDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewDeclarator([NotNull] CPPCXParser.NewDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.noPointerNewDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerNewDeclarator([NotNull] CPPCXParser.NoPointerNewDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.newInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewInitializer([NotNull] CPPCXParser.NewInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.deleteExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeleteExpression([NotNull] CPPCXParser.DeleteExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.noExceptExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoExceptExpression([NotNull] CPPCXParser.NoExceptExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCastExpression([NotNull] CPPCXParser.CastExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.pointerMemberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerMemberExpression([NotNull] CPPCXParser.PointerMemberExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultiplicativeExpression([NotNull] CPPCXParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAdditiveExpression([NotNull] CPPCXParser.AdditiveExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpression([NotNull] CPPCXParser.ShiftExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftOperator([NotNull] CPPCXParser.ShiftOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpression([NotNull] CPPCXParser.RelationalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqualityExpression([NotNull] CPPCXParser.EqualityExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] CPPCXParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExclusiveOrExpression([NotNull] CPPCXParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInclusiveOrExpression([NotNull] CPPCXParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalAndExpression([NotNull] CPPCXParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalOrExpression([NotNull] CPPCXParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalExpression([NotNull] CPPCXParser.ConditionalExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentExpression([NotNull] CPPCXParser.AssignmentExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentOperator([NotNull] CPPCXParser.AssignmentOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CPPCXParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantExpression([NotNull] CPPCXParser.ConstantExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] CPPCXParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledStatement([NotNull] CPPCXParser.LabeledStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionStatement([NotNull] CPPCXParser.ExpressionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompoundStatement([NotNull] CPPCXParser.CompoundStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementSeq([NotNull] CPPCXParser.StatementSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelectionStatement([NotNull] CPPCXParser.SelectionStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] CPPCXParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIterationStatement([NotNull] CPPCXParser.IterationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.forInitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForInitStatement([NotNull] CPPCXParser.ForInitStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.forRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForRangeDeclaration([NotNull] CPPCXParser.ForRangeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.forRangeInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForRangeInitializer([NotNull] CPPCXParser.ForRangeInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJumpStatement([NotNull] CPPCXParser.JumpStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationStatement([NotNull] CPPCXParser.DeclarationStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationseq([NotNull] CPPCXParser.DeclarationseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CPPCXParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.blockDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockDeclaration([NotNull] CPPCXParser.BlockDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.aliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAliasDeclaration([NotNull] CPPCXParser.AliasDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.simpleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleDeclaration([NotNull] CPPCXParser.SimpleDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStaticAssertDeclaration([NotNull] CPPCXParser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.emptyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyDeclaration([NotNull] CPPCXParser.EmptyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeDeclaration([NotNull] CPPCXParser.AttributeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclSpecifier([NotNull] CPPCXParser.DeclSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclSpecifierSeq([NotNull] CPPCXParser.DeclSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorageClassSpecifier([NotNull] CPPCXParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionSpecifier([NotNull] CPPCXParser.FunctionSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypedefName([NotNull] CPPCXParser.TypedefNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifier([NotNull] CPPCXParser.TypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.trailingTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingTypeSpecifier([NotNull] CPPCXParser.TrailingTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeSpecifierSeq([NotNull] CPPCXParser.TypeSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.trailingTypeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingTypeSpecifierSeq([NotNull] CPPCXParser.TrailingTypeSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTypeSpecifier([NotNull] CPPCXParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.theTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheTypeName([NotNull] CPPCXParser.TheTypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.decltypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecltypeSpecifier([NotNull] CPPCXParser.DecltypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.elaboratedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElaboratedTypeSpecifier([NotNull] CPPCXParser.ElaboratedTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumName([NotNull] CPPCXParser.EnumNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumSpecifier([NotNull] CPPCXParser.EnumSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumHead([NotNull] CPPCXParser.EnumHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.opaqueEnumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpaqueEnumDeclaration([NotNull] CPPCXParser.OpaqueEnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumkey([NotNull] CPPCXParser.EnumkeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumbase([NotNull] CPPCXParser.EnumbaseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratorList([NotNull] CPPCXParser.EnumeratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumeratorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumeratorDefinition([NotNull] CPPCXParser.EnumeratorDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumerator([NotNull] CPPCXParser.EnumeratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceName([NotNull] CPPCXParser.NamespaceNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiednamespacespecifier([NotNull] CPPCXParser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.namespaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDefinition([NotNull] CPPCXParser.NamespaceDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.namespaceAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceAliasDefinition([NotNull] CPPCXParser.NamespaceAliasDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.usingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDeclaration([NotNull] CPPCXParser.UsingDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUsingDirective([NotNull] CPPCXParser.UsingDirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.asmDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsmDefinition([NotNull] CPPCXParser.AsmDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.linkageSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLinkageSpecification([NotNull] CPPCXParser.LinkageSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attributeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeSpecifierSeq([NotNull] CPPCXParser.AttributeSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeSpecifier([NotNull] CPPCXParser.AttributeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlignmentspecifier([NotNull] CPPCXParser.AlignmentspecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeList([NotNull] CPPCXParser.AttributeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttribute([NotNull] CPPCXParser.AttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attributeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeNamespace([NotNull] CPPCXParser.AttributeNamespaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.attributeArgumentClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAttributeArgumentClause([NotNull] CPPCXParser.AttributeArgumentClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.balancedTokenSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalancedTokenSeq([NotNull] CPPCXParser.BalancedTokenSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBalancedtoken([NotNull] CPPCXParser.BalancedtokenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclaratorList([NotNull] CPPCXParser.InitDeclaratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitDeclarator([NotNull] CPPCXParser.InitDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarator([NotNull] CPPCXParser.DeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.pointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerDeclarator([NotNull] CPPCXParser.PointerDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.noPointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerDeclarator([NotNull] CPPCXParser.NoPointerDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.parametersAndQualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParametersAndQualifiers([NotNull] CPPCXParser.ParametersAndQualifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.trailingReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTrailingReturnType([NotNull] CPPCXParser.TrailingReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.pointerOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerOperator([NotNull] CPPCXParser.PointerOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCvqualifierseq([NotNull] CPPCXParser.CvqualifierseqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.cvQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCvQualifier([NotNull] CPPCXParser.CvQualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRefqualifier([NotNull] CPPCXParser.RefqualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaratorid([NotNull] CPPCXParser.DeclaratoridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.theTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheTypeId([NotNull] CPPCXParser.TheTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractDeclarator([NotNull] CPPCXParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.pointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPointerAbstractDeclarator([NotNull] CPPCXParser.PointerAbstractDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.noPointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerAbstractDeclarator([NotNull] CPPCXParser.NoPointerAbstractDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.abstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbstractPackDeclarator([NotNull] CPPCXParser.AbstractPackDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.noPointerAbstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoPointerAbstractPackDeclarator([NotNull] CPPCXParser.NoPointerAbstractPackDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.parameterDeclarationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarationClause([NotNull] CPPCXParser.ParameterDeclarationClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.parameterDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclarationList([NotNull] CPPCXParser.ParameterDeclarationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterDeclaration([NotNull] CPPCXParser.ParameterDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionDefinition([NotNull] CPPCXParser.FunctionDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.propertyBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyBody([NotNull] CPPCXParser.PropertyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDefinition([NotNull] CPPCXParser.PropertyDefinitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionBody([NotNull] CPPCXParser.FunctionBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] CPPCXParser.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.braceOrEqualInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBraceOrEqualInitializer([NotNull] CPPCXParser.BraceOrEqualInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.initializerClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerClause([NotNull] CPPCXParser.InitializerClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializerList([NotNull] CPPCXParser.InitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.bracedInitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBracedInitList([NotNull] CPPCXParser.BracedInitListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] CPPCXParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.classSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassSpecifier([NotNull] CPPCXParser.ClassSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassHead([NotNull] CPPCXParser.ClassHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.classHeadName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassHeadName([NotNull] CPPCXParser.ClassHeadNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.classVirtSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassVirtSpecifier([NotNull] CPPCXParser.ClassVirtSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.cxAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCxAttribute([NotNull] CPPCXParser.CxAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.classKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassKey([NotNull] CPPCXParser.ClassKeyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.memberSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberSpecification([NotNull] CPPCXParser.MemberSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberdeclaration([NotNull] CPPCXParser.MemberdeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.memberDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclaratorList([NotNull] CPPCXParser.MemberDeclaratorListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.memberDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberDeclarator([NotNull] CPPCXParser.MemberDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.virtualSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtualSpecifierSeq([NotNull] CPPCXParser.VirtualSpecifierSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.virtualSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVirtualSpecifier([NotNull] CPPCXParser.VirtualSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.pureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPureSpecifier([NotNull] CPPCXParser.PureSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.baseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseClause([NotNull] CPPCXParser.BaseClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.baseSpecifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseSpecifierList([NotNull] CPPCXParser.BaseSpecifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.baseSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseSpecifier([NotNull] CPPCXParser.BaseSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.classOrDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassOrDeclType([NotNull] CPPCXParser.ClassOrDeclTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBaseTypeSpecifier([NotNull] CPPCXParser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessSpecifier([NotNull] CPPCXParser.AccessSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.conversionFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionFunctionId([NotNull] CPPCXParser.ConversionFunctionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.conversionTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionTypeId([NotNull] CPPCXParser.ConversionTypeIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.conversionDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConversionDeclarator([NotNull] CPPCXParser.ConversionDeclaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.constructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstructorInitializer([NotNull] CPPCXParser.ConstructorInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.memInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemInitializerList([NotNull] CPPCXParser.MemInitializerListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.memInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemInitializer([NotNull] CPPCXParser.MemInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeminitializerid([NotNull] CPPCXParser.MeminitializeridContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.operatorFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperatorFunctionId([NotNull] CPPCXParser.OperatorFunctionIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.literalOperatorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralOperatorId([NotNull] CPPCXParser.LiteralOperatorIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateDeclaration([NotNull] CPPCXParser.TemplateDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateparameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateparameterList([NotNull] CPPCXParser.TemplateparameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateParameter([NotNull] CPPCXParser.TemplateParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeParameter([NotNull] CPPCXParser.TypeParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.simpleTemplateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleTemplateId([NotNull] CPPCXParser.SimpleTemplateIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateId([NotNull] CPPCXParser.TemplateIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateName([NotNull] CPPCXParser.TemplateNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateArgumentList([NotNull] CPPCXParser.TemplateArgumentListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.templateArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplateArgument([NotNull] CPPCXParser.TemplateArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typeNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeNameSpecifier([NotNull] CPPCXParser.TypeNameSpecifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.explicitInstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitInstantiation([NotNull] CPPCXParser.ExplicitInstantiationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.explicitSpecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitSpecialization([NotNull] CPPCXParser.ExplicitSpecializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTryBlock([NotNull] CPPCXParser.TryBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.functionTryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionTryBlock([NotNull] CPPCXParser.FunctionTryBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.handlerSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHandlerSeq([NotNull] CPPCXParser.HandlerSeqContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHandler([NotNull] CPPCXParser.HandlerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.exceptionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionDeclaration([NotNull] CPPCXParser.ExceptionDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.throwExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowExpression([NotNull] CPPCXParser.ThrowExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.exceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionSpecification([NotNull] CPPCXParser.ExceptionSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.dynamicExceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDynamicExceptionSpecification([NotNull] CPPCXParser.DynamicExceptionSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.typeIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeIdList([NotNull] CPPCXParser.TypeIdListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.noeExceptSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoeExceptSpecification([NotNull] CPPCXParser.NoeExceptSpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.theOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTheOperator([NotNull] CPPCXParser.TheOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPPCXParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] CPPCXParser.LiteralContext context);
}
