//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from .\CPPCXParser.g4 by ANTLR 4.9

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CPPCXParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9")]
[System.CLSCompliant(false)]
public interface ICPPCXParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTranslationUnit([NotNull] CPPCXParser.TranslationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.translationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTranslationUnit([NotNull] CPPCXParser.TranslationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpression([NotNull] CPPCXParser.PrimaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpression([NotNull] CPPCXParser.PrimaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.idExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdExpression([NotNull] CPPCXParser.IdExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.idExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdExpression([NotNull] CPPCXParser.IdExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.unqualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnqualifiedId([NotNull] CPPCXParser.UnqualifiedIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.unqualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnqualifiedId([NotNull] CPPCXParser.UnqualifiedIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiedId([NotNull] CPPCXParser.QualifiedIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.qualifiedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiedId([NotNull] CPPCXParser.QualifiedIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.nestedNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedNameSpecifier([NotNull] CPPCXParser.NestedNameSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.nestedNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedNameSpecifier([NotNull] CPPCXParser.NestedNameSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaExpression([NotNull] CPPCXParser.LambdaExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.lambdaExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaExpression([NotNull] CPPCXParser.LambdaExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.lambdaIntroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaIntroducer([NotNull] CPPCXParser.LambdaIntroducerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.lambdaIntroducer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaIntroducer([NotNull] CPPCXParser.LambdaIntroducerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.lambdaCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaCapture([NotNull] CPPCXParser.LambdaCaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.lambdaCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaCapture([NotNull] CPPCXParser.LambdaCaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.captureDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaptureDefault([NotNull] CPPCXParser.CaptureDefaultContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.captureDefault"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaptureDefault([NotNull] CPPCXParser.CaptureDefaultContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.captureList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaptureList([NotNull] CPPCXParser.CaptureListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.captureList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaptureList([NotNull] CPPCXParser.CaptureListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCapture([NotNull] CPPCXParser.CaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.capture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCapture([NotNull] CPPCXParser.CaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.simpleCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleCapture([NotNull] CPPCXParser.SimpleCaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.simpleCapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleCapture([NotNull] CPPCXParser.SimpleCaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitcapture([NotNull] CPPCXParser.InitcaptureContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.initcapture"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitcapture([NotNull] CPPCXParser.InitcaptureContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.lambdaDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLambdaDeclarator([NotNull] CPPCXParser.LambdaDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.lambdaDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLambdaDeclarator([NotNull] CPPCXParser.LambdaDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfixExpression([NotNull] CPPCXParser.PostfixExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.postfixExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfixExpression([NotNull] CPPCXParser.PostfixExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typeIdOfTheTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdOfTheTypeId([NotNull] CPPCXParser.TypeIdOfTheTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typeIdOfTheTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdOfTheTypeId([NotNull] CPPCXParser.TypeIdOfTheTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionList([NotNull] CPPCXParser.ExpressionListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionList([NotNull] CPPCXParser.ExpressionListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.pseudoDestructorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPseudoDestructorName([NotNull] CPPCXParser.PseudoDestructorNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.pseudoDestructorName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPseudoDestructorName([NotNull] CPPCXParser.PseudoDestructorNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] CPPCXParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] CPPCXParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] CPPCXParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] CPPCXParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.newExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewExpression([NotNull] CPPCXParser.NewExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.newExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewExpression([NotNull] CPPCXParser.NewExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.newPlacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewPlacement([NotNull] CPPCXParser.NewPlacementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.newPlacement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewPlacement([NotNull] CPPCXParser.NewPlacementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.newTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewTypeId([NotNull] CPPCXParser.NewTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.newTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewTypeId([NotNull] CPPCXParser.NewTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.newDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewDeclarator([NotNull] CPPCXParser.NewDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.newDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewDeclarator([NotNull] CPPCXParser.NewDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.noPointerNewDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerNewDeclarator([NotNull] CPPCXParser.NoPointerNewDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.noPointerNewDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerNewDeclarator([NotNull] CPPCXParser.NoPointerNewDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.newInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNewInitializer([NotNull] CPPCXParser.NewInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.newInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNewInitializer([NotNull] CPPCXParser.NewInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.deleteExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeleteExpression([NotNull] CPPCXParser.DeleteExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.deleteExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeleteExpression([NotNull] CPPCXParser.DeleteExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.noExceptExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoExceptExpression([NotNull] CPPCXParser.NoExceptExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.noExceptExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoExceptExpression([NotNull] CPPCXParser.NoExceptExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCastExpression([NotNull] CPPCXParser.CastExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.castExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCastExpression([NotNull] CPPCXParser.CastExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.pointerMemberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerMemberExpression([NotNull] CPPCXParser.PointerMemberExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.pointerMemberExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerMemberExpression([NotNull] CPPCXParser.PointerMemberExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] CPPCXParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] CPPCXParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] CPPCXParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] CPPCXParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftExpression([NotNull] CPPCXParser.ShiftExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.shiftExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftExpression([NotNull] CPPCXParser.ShiftExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShiftOperator([NotNull] CPPCXParser.ShiftOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.shiftOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShiftOperator([NotNull] CPPCXParser.ShiftOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] CPPCXParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] CPPCXParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] CPPCXParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] CPPCXParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] CPPCXParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] CPPCXParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExclusiveOrExpression([NotNull] CPPCXParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.exclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExclusiveOrExpression([NotNull] CPPCXParser.ExclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInclusiveOrExpression([NotNull] CPPCXParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.inclusiveOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInclusiveOrExpression([NotNull] CPPCXParser.InclusiveOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] CPPCXParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] CPPCXParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] CPPCXParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] CPPCXParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalExpression([NotNull] CPPCXParser.ConditionalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.conditionalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalExpression([NotNull] CPPCXParser.ConditionalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentExpression([NotNull] CPPCXParser.AssignmentExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.assignmentExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentExpression([NotNull] CPPCXParser.AssignmentExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperator([NotNull] CPPCXParser.AssignmentOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.assignmentOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperator([NotNull] CPPCXParser.AssignmentOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CPPCXParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CPPCXParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] CPPCXParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.constantExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] CPPCXParser.ConstantExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CPPCXParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CPPCXParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabeledStatement([NotNull] CPPCXParser.LabeledStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.labeledStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabeledStatement([NotNull] CPPCXParser.LabeledStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionStatement([NotNull] CPPCXParser.ExpressionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.expressionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionStatement([NotNull] CPPCXParser.ExpressionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompoundStatement([NotNull] CPPCXParser.CompoundStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.compoundStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompoundStatement([NotNull] CPPCXParser.CompoundStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementSeq([NotNull] CPPCXParser.StatementSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.statementSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementSeq([NotNull] CPPCXParser.StatementSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelectionStatement([NotNull] CPPCXParser.SelectionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.selectionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelectionStatement([NotNull] CPPCXParser.SelectionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] CPPCXParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] CPPCXParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIterationStatement([NotNull] CPPCXParser.IterationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.iterationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIterationStatement([NotNull] CPPCXParser.IterationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.forInitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInitStatement([NotNull] CPPCXParser.ForInitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.forInitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInitStatement([NotNull] CPPCXParser.ForInitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.forRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForRangeDeclaration([NotNull] CPPCXParser.ForRangeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.forRangeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForRangeDeclaration([NotNull] CPPCXParser.ForRangeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.forRangeInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForRangeInitializer([NotNull] CPPCXParser.ForRangeInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.forRangeInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForRangeInitializer([NotNull] CPPCXParser.ForRangeInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJumpStatement([NotNull] CPPCXParser.JumpStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.jumpStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJumpStatement([NotNull] CPPCXParser.JumpStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationStatement([NotNull] CPPCXParser.DeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationStatement([NotNull] CPPCXParser.DeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationseq([NotNull] CPPCXParser.DeclarationseqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declarationseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationseq([NotNull] CPPCXParser.DeclarationseqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] CPPCXParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] CPPCXParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.blockDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockDeclaration([NotNull] CPPCXParser.BlockDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.blockDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockDeclaration([NotNull] CPPCXParser.BlockDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.aliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAliasDeclaration([NotNull] CPPCXParser.AliasDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.aliasDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAliasDeclaration([NotNull] CPPCXParser.AliasDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.simpleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleDeclaration([NotNull] CPPCXParser.SimpleDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.simpleDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleDeclaration([NotNull] CPPCXParser.SimpleDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStaticAssertDeclaration([NotNull] CPPCXParser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.staticAssertDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStaticAssertDeclaration([NotNull] CPPCXParser.StaticAssertDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.emptyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyDeclaration([NotNull] CPPCXParser.EmptyDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.emptyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyDeclaration([NotNull] CPPCXParser.EmptyDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeDeclaration([NotNull] CPPCXParser.AttributeDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attributeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeDeclaration([NotNull] CPPCXParser.AttributeDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclSpecifier([NotNull] CPPCXParser.DeclSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclSpecifier([NotNull] CPPCXParser.DeclSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclSpecifierSeq([NotNull] CPPCXParser.DeclSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclSpecifierSeq([NotNull] CPPCXParser.DeclSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStorageClassSpecifier([NotNull] CPPCXParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.storageClassSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStorageClassSpecifier([NotNull] CPPCXParser.StorageClassSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSpecifier([NotNull] CPPCXParser.FunctionSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.functionSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSpecifier([NotNull] CPPCXParser.FunctionSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedefName([NotNull] CPPCXParser.TypedefNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typedefName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedefName([NotNull] CPPCXParser.TypedefNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifier([NotNull] CPPCXParser.TypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifier([NotNull] CPPCXParser.TypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.trailingTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailingTypeSpecifier([NotNull] CPPCXParser.TrailingTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.trailingTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailingTypeSpecifier([NotNull] CPPCXParser.TrailingTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpecifierSeq([NotNull] CPPCXParser.TypeSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpecifierSeq([NotNull] CPPCXParser.TypeSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.trailingTypeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailingTypeSpecifierSeq([NotNull] CPPCXParser.TrailingTypeSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.trailingTypeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailingTypeSpecifierSeq([NotNull] CPPCXParser.TrailingTypeSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTypeSpecifier([NotNull] CPPCXParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.simpleTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTypeSpecifier([NotNull] CPPCXParser.SimpleTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.theTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheTypeName([NotNull] CPPCXParser.TheTypeNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.theTypeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheTypeName([NotNull] CPPCXParser.TheTypeNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.decltypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecltypeSpecifier([NotNull] CPPCXParser.DecltypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.decltypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecltypeSpecifier([NotNull] CPPCXParser.DecltypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.elaboratedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElaboratedTypeSpecifier([NotNull] CPPCXParser.ElaboratedTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.elaboratedTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElaboratedTypeSpecifier([NotNull] CPPCXParser.ElaboratedTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumName([NotNull] CPPCXParser.EnumNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumName([NotNull] CPPCXParser.EnumNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumSpecifier([NotNull] CPPCXParser.EnumSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumSpecifier([NotNull] CPPCXParser.EnumSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumHead([NotNull] CPPCXParser.EnumHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumHead([NotNull] CPPCXParser.EnumHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.opaqueEnumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpaqueEnumDeclaration([NotNull] CPPCXParser.OpaqueEnumDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.opaqueEnumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpaqueEnumDeclaration([NotNull] CPPCXParser.OpaqueEnumDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumkey([NotNull] CPPCXParser.EnumkeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumkey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumkey([NotNull] CPPCXParser.EnumkeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumbase([NotNull] CPPCXParser.EnumbaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumbase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumbase([NotNull] CPPCXParser.EnumbaseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorList([NotNull] CPPCXParser.EnumeratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumeratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorList([NotNull] CPPCXParser.EnumeratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumeratorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumeratorDefinition([NotNull] CPPCXParser.EnumeratorDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumeratorDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumeratorDefinition([NotNull] CPPCXParser.EnumeratorDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnumerator([NotNull] CPPCXParser.EnumeratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.enumerator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnumerator([NotNull] CPPCXParser.EnumeratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceName([NotNull] CPPCXParser.NamespaceNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.namespaceName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceName([NotNull] CPPCXParser.NamespaceNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQualifiednamespacespecifier([NotNull] CPPCXParser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.qualifiednamespacespecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQualifiednamespacespecifier([NotNull] CPPCXParser.QualifiednamespacespecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.namespaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceDefinition([NotNull] CPPCXParser.NamespaceDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.namespaceDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceDefinition([NotNull] CPPCXParser.NamespaceDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.namespaceAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespaceAliasDefinition([NotNull] CPPCXParser.NamespaceAliasDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.namespaceAliasDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespaceAliasDefinition([NotNull] CPPCXParser.NamespaceAliasDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.usingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingDeclaration([NotNull] CPPCXParser.UsingDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.usingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingDeclaration([NotNull] CPPCXParser.UsingDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsingDirective([NotNull] CPPCXParser.UsingDirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.usingDirective"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsingDirective([NotNull] CPPCXParser.UsingDirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.asmDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAsmDefinition([NotNull] CPPCXParser.AsmDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.asmDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAsmDefinition([NotNull] CPPCXParser.AsmDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.linkageSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLinkageSpecification([NotNull] CPPCXParser.LinkageSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.linkageSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLinkageSpecification([NotNull] CPPCXParser.LinkageSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attributeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeSpecifierSeq([NotNull] CPPCXParser.AttributeSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attributeSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeSpecifierSeq([NotNull] CPPCXParser.AttributeSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeSpecifier([NotNull] CPPCXParser.AttributeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attributeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeSpecifier([NotNull] CPPCXParser.AttributeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlignmentspecifier([NotNull] CPPCXParser.AlignmentspecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.alignmentspecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlignmentspecifier([NotNull] CPPCXParser.AlignmentspecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeList([NotNull] CPPCXParser.AttributeListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeList([NotNull] CPPCXParser.AttributeListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] CPPCXParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] CPPCXParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attributeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeNamespace([NotNull] CPPCXParser.AttributeNamespaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attributeNamespace"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeNamespace([NotNull] CPPCXParser.AttributeNamespaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.attributeArgumentClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeArgumentClause([NotNull] CPPCXParser.AttributeArgumentClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.attributeArgumentClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeArgumentClause([NotNull] CPPCXParser.AttributeArgumentClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.balancedTokenSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBalancedTokenSeq([NotNull] CPPCXParser.BalancedTokenSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.balancedTokenSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBalancedTokenSeq([NotNull] CPPCXParser.BalancedTokenSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBalancedtoken([NotNull] CPPCXParser.BalancedtokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.balancedtoken"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBalancedtoken([NotNull] CPPCXParser.BalancedtokenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclaratorList([NotNull] CPPCXParser.InitDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.initDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclaratorList([NotNull] CPPCXParser.InitDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitDeclarator([NotNull] CPPCXParser.InitDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.initDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitDeclarator([NotNull] CPPCXParser.InitDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarator([NotNull] CPPCXParser.DeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarator([NotNull] CPPCXParser.DeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.pointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerDeclarator([NotNull] CPPCXParser.PointerDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.pointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerDeclarator([NotNull] CPPCXParser.PointerDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.noPointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerDeclarator([NotNull] CPPCXParser.NoPointerDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.noPointerDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerDeclarator([NotNull] CPPCXParser.NoPointerDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.parametersAndQualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParametersAndQualifiers([NotNull] CPPCXParser.ParametersAndQualifiersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.parametersAndQualifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParametersAndQualifiers([NotNull] CPPCXParser.ParametersAndQualifiersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.trailingReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTrailingReturnType([NotNull] CPPCXParser.TrailingReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.trailingReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTrailingReturnType([NotNull] CPPCXParser.TrailingReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.pointerOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerOperator([NotNull] CPPCXParser.PointerOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.pointerOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerOperator([NotNull] CPPCXParser.PointerOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCvqualifierseq([NotNull] CPPCXParser.CvqualifierseqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.cvqualifierseq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCvqualifierseq([NotNull] CPPCXParser.CvqualifierseqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.cvQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCvQualifier([NotNull] CPPCXParser.CvQualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.cvQualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCvQualifier([NotNull] CPPCXParser.CvQualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRefqualifier([NotNull] CPPCXParser.RefqualifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.refqualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRefqualifier([NotNull] CPPCXParser.RefqualifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaratorid([NotNull] CPPCXParser.DeclaratoridContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.declaratorid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaratorid([NotNull] CPPCXParser.DeclaratoridContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.theTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheTypeId([NotNull] CPPCXParser.TheTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.theTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheTypeId([NotNull] CPPCXParser.TheTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractDeclarator([NotNull] CPPCXParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.abstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractDeclarator([NotNull] CPPCXParser.AbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.pointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerAbstractDeclarator([NotNull] CPPCXParser.PointerAbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.pointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerAbstractDeclarator([NotNull] CPPCXParser.PointerAbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.noPointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerAbstractDeclarator([NotNull] CPPCXParser.NoPointerAbstractDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.noPointerAbstractDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerAbstractDeclarator([NotNull] CPPCXParser.NoPointerAbstractDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.abstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAbstractPackDeclarator([NotNull] CPPCXParser.AbstractPackDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.abstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAbstractPackDeclarator([NotNull] CPPCXParser.AbstractPackDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.noPointerAbstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoPointerAbstractPackDeclarator([NotNull] CPPCXParser.NoPointerAbstractPackDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.noPointerAbstractPackDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoPointerAbstractPackDeclarator([NotNull] CPPCXParser.NoPointerAbstractPackDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.parameterDeclarationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclarationClause([NotNull] CPPCXParser.ParameterDeclarationClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.parameterDeclarationClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclarationClause([NotNull] CPPCXParser.ParameterDeclarationClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.parameterDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclarationList([NotNull] CPPCXParser.ParameterDeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.parameterDeclarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclarationList([NotNull] CPPCXParser.ParameterDeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclaration([NotNull] CPPCXParser.ParameterDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclaration([NotNull] CPPCXParser.ParameterDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] CPPCXParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] CPPCXParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.propertyBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyBody([NotNull] CPPCXParser.PropertyBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.propertyBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyBody([NotNull] CPPCXParser.PropertyBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPropertyDefinition([NotNull] CPPCXParser.PropertyDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.propertyDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPropertyDefinition([NotNull] CPPCXParser.PropertyDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionBody([NotNull] CPPCXParser.FunctionBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.functionBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionBody([NotNull] CPPCXParser.FunctionBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializer([NotNull] CPPCXParser.InitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializer([NotNull] CPPCXParser.InitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.braceOrEqualInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBraceOrEqualInitializer([NotNull] CPPCXParser.BraceOrEqualInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.braceOrEqualInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBraceOrEqualInitializer([NotNull] CPPCXParser.BraceOrEqualInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.initializerClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerClause([NotNull] CPPCXParser.InitializerClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.initializerClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerClause([NotNull] CPPCXParser.InitializerClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitializerList([NotNull] CPPCXParser.InitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.initializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitializerList([NotNull] CPPCXParser.InitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.bracedInitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracedInitList([NotNull] CPPCXParser.BracedInitListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.bracedInitList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracedInitList([NotNull] CPPCXParser.BracedInitListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] CPPCXParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] CPPCXParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.classSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassSpecifier([NotNull] CPPCXParser.ClassSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.classSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassSpecifier([NotNull] CPPCXParser.ClassSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassHead([NotNull] CPPCXParser.ClassHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.classHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassHead([NotNull] CPPCXParser.ClassHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.classHeadName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassHeadName([NotNull] CPPCXParser.ClassHeadNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.classHeadName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassHeadName([NotNull] CPPCXParser.ClassHeadNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.classVirtSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassVirtSpecifier([NotNull] CPPCXParser.ClassVirtSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.classVirtSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassVirtSpecifier([NotNull] CPPCXParser.ClassVirtSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.cxAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCxAttribute([NotNull] CPPCXParser.CxAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.cxAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCxAttribute([NotNull] CPPCXParser.CxAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.classKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassKey([NotNull] CPPCXParser.ClassKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.classKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassKey([NotNull] CPPCXParser.ClassKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.memberSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberSpecification([NotNull] CPPCXParser.MemberSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.memberSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberSpecification([NotNull] CPPCXParser.MemberSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberdeclaration([NotNull] CPPCXParser.MemberdeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.memberdeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberdeclaration([NotNull] CPPCXParser.MemberdeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.memberDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclaratorList([NotNull] CPPCXParser.MemberDeclaratorListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.memberDeclaratorList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclaratorList([NotNull] CPPCXParser.MemberDeclaratorListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.memberDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemberDeclarator([NotNull] CPPCXParser.MemberDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.memberDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemberDeclarator([NotNull] CPPCXParser.MemberDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.virtualSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVirtualSpecifierSeq([NotNull] CPPCXParser.VirtualSpecifierSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.virtualSpecifierSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVirtualSpecifierSeq([NotNull] CPPCXParser.VirtualSpecifierSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.virtualSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVirtualSpecifier([NotNull] CPPCXParser.VirtualSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.virtualSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVirtualSpecifier([NotNull] CPPCXParser.VirtualSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.pureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPureSpecifier([NotNull] CPPCXParser.PureSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.pureSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPureSpecifier([NotNull] CPPCXParser.PureSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.baseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseClause([NotNull] CPPCXParser.BaseClauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.baseClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseClause([NotNull] CPPCXParser.BaseClauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.baseSpecifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseSpecifierList([NotNull] CPPCXParser.BaseSpecifierListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.baseSpecifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseSpecifierList([NotNull] CPPCXParser.BaseSpecifierListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.baseSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseSpecifier([NotNull] CPPCXParser.BaseSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.baseSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseSpecifier([NotNull] CPPCXParser.BaseSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.classOrDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassOrDeclType([NotNull] CPPCXParser.ClassOrDeclTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.classOrDeclType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassOrDeclType([NotNull] CPPCXParser.ClassOrDeclTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseTypeSpecifier([NotNull] CPPCXParser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.baseTypeSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseTypeSpecifier([NotNull] CPPCXParser.BaseTypeSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessSpecifier([NotNull] CPPCXParser.AccessSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.accessSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessSpecifier([NotNull] CPPCXParser.AccessSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.conversionFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversionFunctionId([NotNull] CPPCXParser.ConversionFunctionIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.conversionFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversionFunctionId([NotNull] CPPCXParser.ConversionFunctionIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.conversionTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversionTypeId([NotNull] CPPCXParser.ConversionTypeIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.conversionTypeId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversionTypeId([NotNull] CPPCXParser.ConversionTypeIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.conversionDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConversionDeclarator([NotNull] CPPCXParser.ConversionDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.conversionDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConversionDeclarator([NotNull] CPPCXParser.ConversionDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.constructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstructorInitializer([NotNull] CPPCXParser.ConstructorInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.constructorInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstructorInitializer([NotNull] CPPCXParser.ConstructorInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.memInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemInitializerList([NotNull] CPPCXParser.MemInitializerListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.memInitializerList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemInitializerList([NotNull] CPPCXParser.MemInitializerListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.memInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMemInitializer([NotNull] CPPCXParser.MemInitializerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.memInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMemInitializer([NotNull] CPPCXParser.MemInitializerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeminitializerid([NotNull] CPPCXParser.MeminitializeridContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.meminitializerid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeminitializerid([NotNull] CPPCXParser.MeminitializeridContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.operatorFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperatorFunctionId([NotNull] CPPCXParser.OperatorFunctionIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.operatorFunctionId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperatorFunctionId([NotNull] CPPCXParser.OperatorFunctionIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.literalOperatorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralOperatorId([NotNull] CPPCXParser.LiteralOperatorIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.literalOperatorId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralOperatorId([NotNull] CPPCXParser.LiteralOperatorIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateDeclaration([NotNull] CPPCXParser.TemplateDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateDeclaration([NotNull] CPPCXParser.TemplateDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateparameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateparameterList([NotNull] CPPCXParser.TemplateparameterListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateparameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateparameterList([NotNull] CPPCXParser.TemplateparameterListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateParameter([NotNull] CPPCXParser.TemplateParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateParameter([NotNull] CPPCXParser.TemplateParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeParameter([NotNull] CPPCXParser.TypeParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typeParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeParameter([NotNull] CPPCXParser.TypeParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.simpleTemplateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSimpleTemplateId([NotNull] CPPCXParser.SimpleTemplateIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.simpleTemplateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSimpleTemplateId([NotNull] CPPCXParser.SimpleTemplateIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateId([NotNull] CPPCXParser.TemplateIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateId([NotNull] CPPCXParser.TemplateIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateName([NotNull] CPPCXParser.TemplateNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateName([NotNull] CPPCXParser.TemplateNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateArgumentList([NotNull] CPPCXParser.TemplateArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateArgumentList([NotNull] CPPCXParser.TemplateArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.templateArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateArgument([NotNull] CPPCXParser.TemplateArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.templateArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateArgument([NotNull] CPPCXParser.TemplateArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typeNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeNameSpecifier([NotNull] CPPCXParser.TypeNameSpecifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typeNameSpecifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeNameSpecifier([NotNull] CPPCXParser.TypeNameSpecifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.explicitInstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitInstantiation([NotNull] CPPCXParser.ExplicitInstantiationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.explicitInstantiation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitInstantiation([NotNull] CPPCXParser.ExplicitInstantiationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.explicitSpecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitSpecialization([NotNull] CPPCXParser.ExplicitSpecializationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.explicitSpecialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitSpecialization([NotNull] CPPCXParser.ExplicitSpecializationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTryBlock([NotNull] CPPCXParser.TryBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.tryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTryBlock([NotNull] CPPCXParser.TryBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.functionTryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionTryBlock([NotNull] CPPCXParser.FunctionTryBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.functionTryBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionTryBlock([NotNull] CPPCXParser.FunctionTryBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.handlerSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandlerSeq([NotNull] CPPCXParser.HandlerSeqContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.handlerSeq"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandlerSeq([NotNull] CPPCXParser.HandlerSeqContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHandler([NotNull] CPPCXParser.HandlerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.handler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHandler([NotNull] CPPCXParser.HandlerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.exceptionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionDeclaration([NotNull] CPPCXParser.ExceptionDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.exceptionDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionDeclaration([NotNull] CPPCXParser.ExceptionDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.throwExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterThrowExpression([NotNull] CPPCXParser.ThrowExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.throwExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitThrowExpression([NotNull] CPPCXParser.ThrowExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.exceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExceptionSpecification([NotNull] CPPCXParser.ExceptionSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.exceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExceptionSpecification([NotNull] CPPCXParser.ExceptionSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.dynamicExceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDynamicExceptionSpecification([NotNull] CPPCXParser.DynamicExceptionSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.dynamicExceptionSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDynamicExceptionSpecification([NotNull] CPPCXParser.DynamicExceptionSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.typeIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeIdList([NotNull] CPPCXParser.TypeIdListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.typeIdList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeIdList([NotNull] CPPCXParser.TypeIdListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.noeExceptSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoeExceptSpecification([NotNull] CPPCXParser.NoeExceptSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.noeExceptSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoeExceptSpecification([NotNull] CPPCXParser.NoeExceptSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.theOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTheOperator([NotNull] CPPCXParser.TheOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.theOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTheOperator([NotNull] CPPCXParser.TheOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPPCXParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] CPPCXParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPPCXParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] CPPCXParser.LiteralContext context);
}
